# Generated by Django 5.2 on 2025-05-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bluetooth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Черный', 'Черный'), ('Коричневый', 'Коричневый'), ('Белый', 'Белый'), ('Палисандр', 'Палисандр'), ('Серый', 'Серый'), ('Красный', 'Красный'), ('Синий', 'Синий'), ('Жёлтый', 'Жёлтый')], default='Черный', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='functions',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='hammer_keyboard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='interfaces',
            field=models.CharField(default='USB', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='key_size',
            field=models.CharField(choices=[('Полуразмерная', 'Полуразмерная'), ('Полноразмерная', 'Полноразмерная')], default='Полноразмерная', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='key_weight',
            field=models.CharField(choices=[('Взвешенная', 'Взвешенная'), ('Невзвешенная', 'Невзвешенная'), ('Полувзвешенная', 'Полувзвешенная')], default='Невзвешенная', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='keys',
            field=models.PositiveIntegerField(choices=[(61, '61'), (68, '68'), (73, '73'), (76, '76'), (88, '88')], default=88),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(choices=[('Yamaha', 'Yamaha'), ('Casio', 'Casio'), ('Roland', 'Roland'), ('Artesia', 'Artesia'), ('Virtuozo', 'Virtuozo'), ('Ringway', 'Ringway')], default='Yamaha', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='metronome',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='polyphony',
            field=models.PositiveIntegerField(choices=[(16, '16'), (32, '32'), (48, '48'), (64, '64'), (80, '80'), (128, '128'), (256, '256')], default=64),
        ),
        migrations.AddField(
            model_name='product',
            name='power',
            field=models.CharField(default='От сети 220В', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='recorder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='Стандартные', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='sound_effects',
            field=models.CharField(default='Reverb', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='tones',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.CharField(default='12 месяцев', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.PositiveIntegerField(default=15000),
        ),
    ]
