# Generated by Django 5.2 on 2025-05-22 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_product_bluetooth_product_color_product_functions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='functions',
        ),
    ]
